---
collections:
  # Install a collection from Ansible Galaxy.
  - name: veeamhub.veeam
    version: 2.2.3
    source: https://galaxy.ansible.com

  - name: ansible.windows
    version: 2.2.0
    source: https://galaxy.ansible.com

  - name: community.windows
    version: 2.1.0
    source: https://galaxy.ansible.com